# File generated from our OpenAPI spec by Scalar. See README.md for details.

from __future__ import annotations

from .document_create_v1_id_post_params import DocumentCreateV1IDPostParams as DocumentCreateV1IDPostParams
from .document_update_v1_id_put_params import DocumentUpdateV1IDPutParams as DocumentUpdateV1IDPutParams
from .document_delete_v1_id_delete_params import DocumentDeleteV1IDDeleteParams as DocumentDeleteV1IDDeleteParams
from .folder_create_v1_id_post_response import FolderCreateV1IDPostResponse as FolderCreateV1IDPostResponse
from .folder_create_v1_id_post_params import FolderCreateV1IDPostParams as FolderCreateV1IDPostParams
from .folder_delete_v1_id_delete_response import FolderDeleteV1IDDeleteResponse as FolderDeleteV1IDDeleteResponse
from .folder_delete_v1_id_delete_params import FolderDeleteV1IDDeleteParams as FolderDeleteV1IDDeleteParams
