# Generated by scripts/generate_filter_table.py from the x-profound-filter-grammar extension of the Profound OpenAPI spec. Do not edit by hand.

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Final, Literal, Tuple


@dataclass(frozen=True)
class FieldSpec:
    name: str
    layer: Literal["prompt", "entity"]
    ops: Tuple[str, ...]


MAX_DEPTH: Final = 3

FIELD_TABLE: Final[Dict[str, FieldSpec]] = {
    "analysis_type": FieldSpec("analysis_type", "entity", ("is", "not_is", "in", "not_in")),
    "citation_category": FieldSpec("citation_category", "entity", ("is", "in")),
    "citation_tag": FieldSpec("citation_tag", "entity", ("is", "in")),
    "claim": FieldSpec("claim", "entity", ("is", "in")),
    "domain": FieldSpec(
        "domain",
        "entity",
        (
            "is",
            "not_is",
            "in",
            "not_in",
            "contains",
            "not_contains",
            "matches",
            "contains_case_insensitive",
            "not_contains_case_insensitive",
        ),
    ),
    "model": FieldSpec(
        "model",
        "prompt",
        (
            "is",
            "not_is",
            "in",
            "not_in",
            "contains",
            "not_contains",
            "matches",
            "contains_case_insensitive",
            "not_contains_case_insensitive",
        ),
    ),
    "page": FieldSpec(
        "page",
        "entity",
        (
            "is",
            "not_is",
            "in",
            "not_in",
            "contains",
            "not_contains",
            "matches",
            "contains_case_insensitive",
            "not_contains_case_insensitive",
        ),
    ),
    "persona": FieldSpec(
        "persona",
        "prompt",
        (
            "is",
            "not_is",
            "in",
            "not_in",
            "contains",
            "not_contains",
            "matches",
            "contains_case_insensitive",
            "not_contains_case_insensitive",
            "exists",
        ),
    ),
    "prompt": FieldSpec(
        "prompt",
        "prompt",
        (
            "is",
            "not_is",
            "in",
            "not_in",
            "contains",
            "not_contains",
            "matches",
            "contains_case_insensitive",
            "not_contains_case_insensitive",
        ),
    ),
    "region": FieldSpec(
        "region",
        "prompt",
        (
            "is",
            "not_is",
            "in",
            "not_in",
            "contains",
            "not_contains",
            "matches",
            "contains_case_insensitive",
            "not_contains_case_insensitive",
        ),
    ),
    "tag": FieldSpec(
        "tag",
        "prompt",
        (
            "is",
            "not_is",
            "in",
            "not_in",
            "contains",
            "not_contains",
            "matches",
            "contains_case_insensitive",
            "not_contains_case_insensitive",
            "exists",
        ),
    ),
    "theme": FieldSpec("theme", "entity", ("is", "in")),
    "topic": FieldSpec(
        "topic",
        "prompt",
        (
            "is",
            "not_is",
            "in",
            "not_in",
            "contains",
            "not_contains",
            "matches",
            "contains_case_insensitive",
            "not_contains_case_insensitive",
        ),
    ),
}


class Fields:
    analysis_type: Final = FIELD_TABLE["analysis_type"]
    citation_category: Final = FIELD_TABLE["citation_category"]
    citation_tag: Final = FIELD_TABLE["citation_tag"]
    claim: Final = FIELD_TABLE["claim"]
    domain: Final = FIELD_TABLE["domain"]
    model: Final = FIELD_TABLE["model"]
    page: Final = FIELD_TABLE["page"]
    persona: Final = FIELD_TABLE["persona"]
    prompt: Final = FIELD_TABLE["prompt"]
    region: Final = FIELD_TABLE["region"]
    tag: Final = FIELD_TABLE["tag"]
    theme: Final = FIELD_TABLE["theme"]
    topic: Final = FIELD_TABLE["topic"]
