#!/usr/bin/env python3

from __future__ import annotations

import json
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

REGISTRY_URL = "https://registry.scalar.com/@profound/apis/external-api/latest?format=json"
OUTPUT = Path(__file__).parents[1] / "src" / "profound" / "lib" / "filter_table.py"


def load_spec(source: str) -> dict[str, Any]:
    if source.startswith(("http://", "https://")):
        with urllib.request.urlopen(source) as response:
            return json.load(response)
    with Path(source).open(encoding="utf-8") as file:
        return json.load(file)


def generate(spec: dict[str, Any]) -> str:
    grammar = spec.get("x-profound-filter-grammar")
    if not grammar:
        raise ValueError("spec has no x-profound-filter-grammar extension")

    lines = [
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from typing import Dict, Final, Literal, Tuple",
        "",
        "",
        "@dataclass(frozen=True)",
        "class FieldSpec:",
        "    name: str",
        '    layer: Literal["prompt", "entity"]',
        "    ops: Tuple[str, ...]",
        "",
        "",
        f"MAX_DEPTH: Final = {grammar['max_depth']}",
        "",
        "FIELD_TABLE: Final[Dict[str, FieldSpec]] = {",
    ]
    for name, field in grammar["fields"].items():
        ops = ", ".join(repr(op) for op in field["ops"])
        if len(field["ops"]) == 1:
            ops += ","
        lines.extend(
            [
                f"    {name!r}: FieldSpec({name!r}, {field['layer']!r}, ({ops})),",
            ]
        )
    lines.extend(["}", "", "", "class Fields:"])
    for name in grammar["fields"]:
        lines.append(f"    {name}: Final = FIELD_TABLE[{name!r}]")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    source = sys.argv[1] if len(sys.argv) > 1 else REGISTRY_URL
    try:
        content = generate(load_spec(source))
    except (OSError, ValueError, json.JSONDecodeError, urllib.error.URLError) as error:
        print(f"failed to generate filter table: {error}", file=sys.stderr)
        return 1
    OUTPUT.write_text(
        "# Generated by scripts/generate_filter_table.py from the x-profound-filter-grammar extension "
        "of the Profound OpenAPI spec. Do not edit by hand.\n\n" + content,
        encoding="utf-8",
    )
    subprocess.run(["ruff", "format", str(OUTPUT)], check=True)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
